crowdfunder/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :projects do
    resources :rewards
    resources :rewards_users
  end
  resources :users, only: [:show]


  root "projects#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

crowdfunder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crowdfunder/app/models/project.rb
class Project < ApplicationRecord
  has_many :rewards
  has_many :users, through: :rewards
  belongs_to :owner, class_name: User, foreign_key: "user_id"
  accepts_nested_attributes_for :rewards

  def all_pledges_total
    rewards.inject(0) {|sum,reward| sum + reward.pledges_total}
  end
end

crowdfunder/app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :project, optional: true
  has_many :rewards_users
  has_many :users, through: :rewards_users

  def pledges_total
    rewards_users.count * pledge
  end

end

crowdfunder/app/models/rewards_user.rb
class RewardsUser < ApplicationRecord
  belongs_to :user
  belongs_to :reward
end

crowdfunder/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards_users
  has_many :rewards, through: :rewards_users
  has_many :owned_projects, class_name: Project
end

crowdfunder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

crowdfunder/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    
  end

  # my_project.rewards

  def new
    if current_user
    @project = Project.new
    @reward = Reward.new
  else
    redirect_to projects_path
  end
  end

  def create
    user_signed_in?
    @project = Project.new(project_params)
    @project.owner = current_user
    puts project_params
      if @project.save
        redirect_to @project
      else
        render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @rewards = @project.rewards.all
    # @rewards = Reward.find(params[:project_id])
  end

  def destroy
    current_user
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def edit
    current_user
    @project = Project.find(params[:id])
  end

  def update
    current_user
    @project = Project.find(params[:id])
      if @project.update_attributes(project_params)
        redirect_to projects_path
      else
        render :edit
      end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :goal, :image, :end_date, rewards_attributes: [:title, :description, :pledge])
  end

  def load_project
    @project = Project.find(params[:project_id])
  end

end

crowdfunder/app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
before_action :load_project

end

crowdfunder/app/controllers/rewards_users_controller.rb
class RewardsUsersController < ApplicationController
  def create
  @reward = Reward.where(project_id: params[:project_id]).first
  @user = current_user
  @rewards_user = RewardsUser.create(user: @user, reward: @reward)
  end

end

crowdfunder/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    # @rewards = RewardsUser.where(user_id: @user)
    # @projects = Project.where(user_id: @user)
  end
end

crowdfunder/app/helpers/application_helper.rb
module ApplicationHelper
end

crowdfunder/app/helpers/projects_helper.rb
module ProjectsHelper
end

crowdfunder/app/helpers/rewards_helper.rb
module RewardsHelper
end

crowdfunder/app/helpers/rewards_users_helper.rb
module RewardsUsersHelper
end

crowdfunder/app/helpers/users_helper.rb
module UsersHelper
end

crowdfunder/app/views/layouts/_usertools.html.erb
<% if user_signed_in? %>
<div class="user-tools">
  <li>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
  <% else %>
  <li>
    <%= link_to('Login', new_user_session_path)  %>
  </li>
  <li>
    <%= link_to('Sign Up', new_user_registration_path)  %>
  </li>
</div>
<% end %>

crowdfunder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfunder</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-content">
      <div class="user-tools">
      <% if user_signed_in? %>
        <li>
        <%= link_to("Welcome, #{current_user.email}", current_user) %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
        <li>
          <%= link_to "Create a project", new_project_path %>
        </li>
        <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <li>
          <%= link_to('Sign Up', new_user_registration_path)  %>
        </li>
        <% end %>
      </div>
    </div>
    </header>
    <div class="main-content">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to image_tag("https://www.kickstarter.com/download/kickstarter-logo-light.png", :class => "logo"), root_path %>
    <main><%= yield %></main>
  </div>
  </body>
</html>

crowdfunder/app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |f| %>
<div class="field">
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div class="field">
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div class="field">
<%= f.label :goal %>
<%= f.number_field :goal %>
</div>
<div class="field">
<%= f.label :end_date %>
<%= f.date_select :end_date %>
</div>
<div class="field">
<%= f.label :image %>
<%= f.text_field :image %>
</div>

<h2>Set your rewards</h2>

<%= f.fields_for :rewards, @reward do |r| %>
  <div class="field">
  <%= r.label :title %>
  <%= r.text_field :title  %>
  </div>
  <div class="field">
  <%= r.label :description %>
  <%= r.text_area :description %>
  </div>
  <div class="field">
  <%= r.label :pledge %>
  <%= r.number_field :pledge %>
  </div>
<% end %>

<%= f.submit "Save Project" %>
<% end %>

crowdfunder/app/views/projects/index.html.erb
<container class = "body_container">
  <div class = "featured">
    <div class = "header_img"><%= link_to image_tag(Project.last.image), project_path(Project.last)%></div>
    <div class="project_of_day">Project of the Day</div>
  </div>

  <div class = "header2">Projects We Love</div>

  <div class = "list-projects">
    <% @projects.each do |p| %>
      <ul class = "list-items">
        <% if p == @projects.last %>
        <% else %>
          <li class = "list-image"><%= link_to image_tag(p.image), project_path(p) %></li>
          <div class = "list-description">
            <li class = "title"><%= p.title %></li>
            <li class = "description"><%= p.description %></li>
            <li class= "time-left">Time left: <%= ((((p.end_date.to_time) - Time.now)/3600)/24).to_i %> days</li>
          </div>
        <% end %>
      </ul>
    <% end %>
  </div>
</container>

crowdfunder/app/views/projects/new.html.erb
<h1>Create a project</h1>

<h2>Enter project details</h2>

<%= form_for @project do |f| %>
<div class="project-field">
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div class="project-field">
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div class="project-field">
<%= f.label :goal %>
<%= f.number_field :goal %>
</div>
<div class="project-field">
<%= f.label :end_date %>
<%= f.date_select :end_date %>
</div>
<div class="project-field">
<%= f.label :image %>
<%= f.text_field :image %>
</div>

<h2>Set your rewards</h2>

<%= f.fields_for :rewards, @reward do |r| %>
  <div class="project-field">
  <%= r.label :title %>
  <%= r.text_field :title  %>
  </div>
  <div class="project-field">
  <%= r.label :description %>
  <%= r.text_area :description %>
  </div>
  <div class="project-field">
  <%= r.label :pledge %>
  <%= r.number_field :pledge %>
  </div>
<% end %>

<div class="project-actions"><%= f.submit "Start Project" %></div>
<% end %>

crowdfunder/app/views/projects/show.html.erb
<div class="project-main">
  <h1><%= @project.title %></h1>
    <h4>Our goal: $<%= @project.goal %>.00</h4>
    <h4>Amount Raised: $<%= @project.all_pledges_total %>.00</h4>
  <div class="project-description">
    <p><%= @project.description %></p>
  </div>
  <%= image_tag @project.image, :class => "show-image" %>
</div>
<div class="rewards">

<% @rewards.each do |reward| %>
  <h2 class="reward-name"><%= link_to reward.title, project_rewards_users_path(@project), :method => :post %></h2>
  <p><%= reward.description %></p>
  <h4>$<%= reward.pledge %>.00</h4>
</div>
<% end %>

crowdfunder/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1 class = "user-header"> Welcome Back!</h1>
    <p class = "user-information"><strong>Account name: </strong><%= @user.email %></p>
    <p class = "user-information"><strong>Last logged in: </strong><%= @user.last_sign_in_at %></p>
    <h1 class = "header2">Projects You Have Backed</h1>
    <div class = "list-projects">
    <% if @user.rewards.empty? %>
      <p class = "no-backed-projects">You don't have any backed projects</p>
      <p class = "no-backed-projects"><%= link_to "Explore projects to back!", projects_path %></p>
    <% else %>
      <% @user.rewards.each do |reward| %>

      <ul class = "list-items">
        <li class = "list-image"><%= link_to image_tag(reward.project.image), project_path(reward.project)%></li>
        <div class = "list-description">
        <li class = "title"><%= reward.project.title %></li>
        <li class = "description">Amount Pledged: $<%= reward.pledge %>.00</li>
        <li class = "description">Time left: <%= ((((reward.project.end_date.to_time) - Time.now)/3600)/24).to_i %> days</li>
      </div>
      </ul>
      <% end %>
    <% end %>
    </div>

    <h1 class = "header2">My Projects</h1>
    <% if @user.owned_projects.empty? %>
      <p class = "no-backed-projects">You don't have any projects</p>
      <p class = "no-backed-projects"><%= link_to "Create a project here", new_project_path %></p>
    <% else %>
      <% @user.owned_projects.each do |project| %>
      <ul class = "list-items">
        <li class = "list-image"><%= link_to image_tag(project.image), project_path(project) %></li>
        <div class = "list-description">
        <li class = "title"><%= project.title %></li>
        <li class = "description">Amount Raised: $<%= project.all_pledges_total %>.00</li>
        <li class = "description">Time left: <%= ((((project.end_date.to_time) - Time.now) /3600)/24).to_i %> days</li>
      </div>
      </ul>
      <% end %>
    <% end %>
  </body>
</html>